### ISSUE TITLE
As an unregistered user, I want to be able to register as a user with my chosen credentials (email address, password, username) to leverage/use services and information that are exclusively available to registered users.  

### ISSUE THREAD

**Issue by oaboha** [sopra-fs22-group-20/server#1]
- [ ] sopra-fs22-group-20/server#17
- [ ] sopra-fs22-group-20/server#18
- [ ] sopra-fs22-group-20/client#1
- [ ] sopra-fs22-group-20/server#20
- [ ] sopra-fs22-group-20/client#2
- [ ] sopra-fs22-group-20/server#61
- [ ] sopra-fs22-group-20/client#23
