### ISSUE TITLE
As a registered and logged-in user, I want to be able to edit my profile to set/update my personal information so my profile can always be up to date.

### ISSUE THREAD

**Issue by oaboha** [sopra-fs22-group-20/server#189]
**Acceptance Criteria**
- [x] User can change password and username
- [x] After changing and saving the data, the new user data is directly shown

**Development Tasks FE**
- [x] sopra-fs22-group-20/client#29
- [x] sopra-fs22-group-20/client#30
- [x] sopra-fs22-group-20/client#31
- [x] sopra-fs22-group-20/client#33
- [x] sopra-fs22-group-20/client#34

**Development Tasks BE**
- [x] sopra-fs22-group-20/server#188
