### ISSUE TITLE
As a registered and logged-in user, I want to be able to play a game (Egg ^^) where I can earn “trophies” in order to boost a specific pictures.

### ISSUE THREAD

**Issue by oaboha** [sopra-fs22-group-20/server#307]
**Acceptance Criteria**
- [x] On the home page I can click on a button and I am redirected to the game page
- [x] On the game page I am pooled with other players
- [x] If there is another player found the game starts
- [x] When the game starts you are redirected to the match
- [x] In the end, the winner gets a trophy

**Development Tasks FE**
- [x] sopra-fs22-group-20/client#122
- [x] sopra-fs22-group-20/client#123
- [x] sopra-fs22-group-20/client#124
- [x] sopra-fs22-group-20/client#171
- [x] sopra-fs22-group-20/client#159
- [x] sopra-fs22-group-20/client#160
- [x] sopra-fs22-group-20/client#161
- [x] sopra-fs22-group-20/client#162
- [x] sopra-fs22-group-20/client#164
- [x] sopra-fs22-group-20/client#172
- [x] sopra-fs22-group-20/client#170
- [x] sopra-fs22-group-20/client#169
- [x] sopra-fs22-group-20/client#168
- [x] sopra-fs22-group-20/client#167
- [x] sopra-fs22-group-20/client#166
- [x] sopra-fs22-group-20/client#165
- [x] sopra-fs22-group-20/client#163

**Development Tasks BE**
- [x] sopra-fs22-group-20/server#212
- [x] sopra-fs22-group-20/server#213
- [x] sopra-fs22-group-20/server#278
- [x] sopra-fs22-group-20/server#279 
- [x] sopra-fs22-group-20/server#280
- [x] sopra-fs22-group-20/server#281 
- [x] sopra-fs22-group-20/server#282 
- [x] sopra-fs22-group-20/server#283
- [x] sopra-fs22-group-20/server#284
- [x] sopra-fs22-group-20/server#285
