### ISSUE TITLE
As an unregistered user, I want to be able to register as a user with my chosen credentials (email address, password, username) to leverage/use services and information that are exclusively available to registered users. 

### ISSUE THREAD

**Issue by oaboha** [sopra-fs22-group-20/server#66]
**Acceptance Criteria**

- [x] The given username and email must be unique 
- [x] Upon successful user registration, the user's overview screen (see below) is shown, and the user is automatically logged in
- [x] Upon failure, an error is displayed, and the user is redirected (back) to the register screen
- [x] You are automaticall logged in

**Development Tasks FE**
- [x] sopra-fs22-group-20/client#35
- [x] sopra-fs22-group-20/client#36
- [x] sopra-fs22-group-20/client#37
- [x] sopra-fs22-group-20/client#38
- [x] sopra-fs22-group-20/client#39
- [x] sopra-fs22-group-20/client#40

**Development Tasks BE**
- [x] sopra-fs22-group-20/server#98
- [x] sopra-fs22-group-20/server#99
- [x] sopra-fs22-group-20/server#100
- [x] sopra-fs22-group-20/server#101
- [x] sopra-fs22-group-20/server#102
- [x] sopra-fs22-group-20/server#103
