### ISSUE TITLE
As a registered user, I want to be able to log in to my account by inserting my user credentials (email and password) to get access to the account and the service.

### ISSUE THREAD

**Issue by oaboha** [sopra-fs22-group-20/server#67]
**Acceptance Criteria**
- [x]  Users can log back into their registered proﬁle

**Development Tasks FE**
- [x] sopra-fs22-group-20/client#41
- [x] sopra-fs22-group-20/client#42
- [x] sopra-fs22-group-20/client#43
- [x] sopra-fs22-group-20/client#44
- [x] sopra-fs22-group-20/client#45

**Development Tasks BE**
- [x] sopra-fs22-group-20/server#109
