### ISSUE TITLE
As a logged in user, I want to logout from the site from every page in order to leave the website.

### ISSUE THREAD

**Issue by oaboha** [sopra-fs22-group-20/server#68]
**Acceptance Criteria**
- [x] On every page, there should be a logout button

**Development Tasks FE**
- [x] sopra-fs22-group-20/client#46
- [x] sopra-fs22-group-20/client#47
- [x] sopra-fs22-group-20/client#48

**Development Tasks BE**
- [x] #256
