### ISSUE TITLE
As a registered and logged-in user, I want to be able to upload a picture and set its properties (name, etc.) so others can rate it and I get rating points to higher my chances of appearing in the weekly highlights.

### ISSUE THREAD

**Issue by oaboha** [sopra-fs22-group-20/server#69]
**Acceptance Criteria**
- [x] The user can upload his picture which is then saved into a database
- [x] The users can type in the name and set an optional location

**Development Tasks FE**
- [x] sopra-fs22-group-20/client#49
- [x] sopra-fs22-group-20/client#50
- [x] sopra-fs22-group-20/client#51
- [x] sopra-fs22-group-20/client#52
- [x] sopra-fs22-group-20/client#53
- [x] sopra-fs22-group-20/client#54
- [x] sopra-fs22-group-20/client#55
- [x] sopra-fs22-group-20/client#56

**Development Tasks BE**
- [x] #122
- [x] #123
- [x] #124
- [x] #125
- [x] #257
- [x] #263
