### ISSUE TITLE
As a registered and logged-in user, I want to be able to tag where I took the picture so people know where I took it when I am uploading a picture. 

### ISSUE THREAD

**Issue by oaboha** [sopra-fs22-group-20/server#70]
**Acceptance Criteria**
- [x] The user can skip this step if he does not want to give the location of the image
- [x] I want set the location based on my current location
- [x] I want to be able to set the location manually. (Not there where I took it)

**Development Tasks FE**
- [x] sopra-fs22-group-20/client#58
- [x] sopra-fs22-group-20/client#59
- [x] sopra-fs22-group-20/client#60
- [x] sopra-fs22-group-20/client#148 
- [x] sopra-fs22-group-20/client#149 
- [x] sopra-fs22-group-20/client#150 
- [x] sopra-fs22-group-20/client#147 
- [x] sopra-fs22-group-20/client#153

**Development Tasks BE**
- [x] sopra-fs22-group-20/server#129
- [x] sopra-fs22-group-20/server#130
- [x] sopra-fs22-group-20/server#131
- [x] sopra-fs22-group-20/server#132
