### ISSUE TITLE
As a registered and logged-in user, I want to see an overview of my uploaded pictures to see my pictures. 

### ISSUE THREAD

**Issue by oaboha** [sopra-fs22-group-20/server#72]
**Acceptance Criteria**
- [x] A user can get an overview of his/her own photos on his/her own profile page

**Development Tasks FE**
- [x] sopra-fs22-group-20/client#61
- [x] sopra-fs22-group-20/client#62
- [x] sopra-fs22-group-20/client#63
- [x] sopra-fs22-group-20/client#64
- [x] sopra-fs22-group-20/client#65
- [x] sopra-fs22-group-20/client#66

**Development Tasks BE**
- [x] #141
