### ISSUE TITLE
As a registered and logged-in user, I want to have the ability to delete my uploaded pictures to get rid of unwanted pictures.

### ISSUE THREAD

**Issue by oaboha** [sopra-fs22-group-20/server#73]
**Acceptance Criteria**
- [x] A user can delete his own pictures

**Development Tasks FE**
- [x] sopra-fs22-group-20/client#67
- [x] sopra-fs22-group-20/client#68
- [x] sopra-fs22-group-20/client#69
- [x] sopra-fs22-group-20/client#70
- [x] sopra-fs22-group-20/client#75

**Development Tasks BE**
- [x] #152
- [x] #153
