### ISSUE TITLE
As a registered and logged-in user, I want to be able to edit the properties of my photo to make changes if they don't match my original specifications

### ISSUE THREAD

**Issue by oaboha** [sopra-fs22-group-20/server#74]
**Acceptance Criteria**
- [ ] A user can set a new name for his photo
- [ ] A user can trade his trophies for a boost

**Development Tasks FE**
- [ ] sopra-fs22-group-20/client#77
- [ ] sopra-fs22-group-20/client#78
- [ ] sopra-fs22-group-20/client#79
- [ ] sopra-fs22-group-20/client#80
- [ ] sopra-fs22-group-20/client#81
- [ ] sopra-fs22-group-20/client#82
- [ ] sopra-fs22-group-20/client#83
- [ ] sopra-fs22-group-20/client#84
- [x] sopra-fs22-group-20/client#154

**Development Tasks BE**
- [ ] #162

**Comment by kone54** [comment]
- [ ] Can category be set differently later on (pro: if new categroeis are added according to request, can assign picture to it; contra: you can try to be on highlights per category by simply change category

**Comment by oaboha** [comment]
Changing the title does not make sense here in pictures because in home the title will be not shown anyways. Also the idea is that a user can delete a picture if he made a mistake with the tile. Therefore this user story will be deleted.
