### ISSUE TITLE
As a registered and logged-in user, I want to be able to see pictures of other users in order to give them a feedback.

### ISSUE THREAD

**Issue by oaboha** [sopra-fs22-group-20/server#75]
**Acceptance Criteria**
- [x] The pictures are shown on the home/start page
- [x] The pictures are fetched from the database and shown to the users
- [x] The order in which the pictures are shown is random, but some are classified more often due to the game
- [x] Only one image of one specific user can be seen at a time
- [x] After given feed, you get a new picture
- [x] Every picture is only shown once to a user; if rated, the picture is never shown to the same user again

**Development Tasks FE**
- [x] sopra-fs22-group-20/client#85
- [x] sopra-fs22-group-20/client#86
- [x] sopra-fs22-group-20/client#87

**Development Tasks BE**
- [x] #168
