### ISSUE TITLE
As a registered and logged-in user, I want to be able to rate the shown pictures  to rate them

### ISSUE THREAD

**Issue by oaboha** [sopra-fs22-group-20/server#76]
**Acceptance Criteria**
- [x] A user can give up to five stars to a picture
- [x] The rating is added to the picture in the database
- [x] The Image_id is added to the user who rated it so he will not see it again

**Development Tasks FE**
- [x] sopra-fs22-group-20/client#89
- [x] sopra-fs22-group-20/client#90
- [x] sopra-fs22-group-20/client#91
- [x] sopra-fs22-group-20/client#92
- [x] sopra-fs22-group-20/client#93
- [x] sopra-fs22-group-20/client#94
- [x] sopra-fs22-group-20/client#95

**Development Tasks BE**
- [x] sopra-fs22-group-20/server#187

**Comment by kone54** [comment]
*DISCUSSION*: should the image store the id of users that rated it or should the user store id of images that he/she has already rated?
