### ISSUE TITLE
As a registered and logged-in user, I want to be able to see the weekly highlights of the best rated pictures from the last 7 days in order to see what is popular. 

### ISSUE THREAD

**Issue by oaboha** [sopra-fs22-group-20/server#77]
**Acceptance Criteria**
- [x] As a user, I want to get to a weekly highlights page by clicking a button in the navigation bar
- [x] On the weekly highlights page, I can choose a category and then the current best rated pictures are shown

**Development Tasks FE**
- [x] sopra-fs22-group-20/client#97
- [x] sopra-fs22-group-20/client#99
- [x] sopra-fs22-group-20/client#101
- [x] sopra-fs22-group-20/client#103
- [x] sopra-fs22-group-20/client#155

**Development Tasks BE**
- [x] sopra-fs22-group-20/server#185
