### ISSUE TITLE
As a registered and logged-in user,  if there is no suitable category I want to be able to recommend a new one to the the admins to get a suitable cagtegory for my picture

### ISSUE THREAD

**Issue by oaboha** [sopra-fs22-group-20/server#78]
**Acceptance Criteria**
- [x] A user can optionally make proposals for new categories by clicking on a suggest category button in the category overview pop up window
- [x] The request on a basic page, where you insert the new category and send it by clicking on the button
- [x] The message is sent via email to a predefined email address 

**Development Tasks FE**
- [x] sopra-fs22-group-20/client#141
- [x] sopra-fs22-group-20/client#142
- [x] sopra-fs22-group-20/client#143
- [x] sopra-fs22-group-20/client#151

**Development Tasks BE**
