### ISSUE TITLE
As a registered and logged-in user, I want to be able to share links to pictures that I like with my friends to get other people to see this specific picture.

### ISSUE THREAD

**Issue by oaboha** [sopra-fs22-group-20/server#81]
**Acceptance Criteria**
- [x] sopra-fs22-group-20/client#109
- [x] sopra-fs22-group-20/client#110
- [x] sopra-fs22-group-20/client#111
- [x] sopra-fs22-group-20/client#112

**Development Tasks FE**
- [x] sopra-fs22-group-20/server#198

**Development Tasks BE**

**Comment by oaboha** [comment]
We decide not to implement this function because of the principle of randomness in our application. We don't want famous people to post the link on Instagram and get many likes for a specific picture.
