### ISSUE TITLE
As a registered and logged-in user, I want to be able to check out the profile of the users that made it into the weekly highlight and see other social media of him/her such as Instagram etc.

### ISSUE THREAD

**Issue by oaboha** [sopra-fs22-group-20/server#82]
**Acceptance Criteria**
- [x] This profile page does not contain other data such as pictures. It only means is to allow people to read their bio and see information about the profile and links to Instagram
- [x] You are only able to check out the profile page of a user that made it into the weekly highlights. You will not be able to edit the properties (password, Instagram, information field) of that user. 

**Development Tasks FE**
- [x] sopra-fs22-group-20/client#116
- [x] sopra-fs22-group-20/client#117
- [x] sopra-fs22-group-20/client#118
- [x] sopra-fs22-group-20/client#119
- [x] sopra-fs22-group-20/client#120
- [x] sopra-fs22-group-20/client#121

**Development Tasks BE**
- [x] sopra-fs22-group-20/server#208
