### ISSUE TITLE
As a user, I can trade my trophies that I have won in a game for a boost to a selected picture’s rating algorithm to get a better chance of appearing in the weekly highlights

### ISSUE THREAD

**Issue by kone54** [sopra-fs22-group-20/server#91]
**Acceptance Criteria**
- [x] A user sees the overall number of trophies he currently owns on every page
- [x] *OPTIONAL*: By hovering with the mouse over the trophies, there is a description of what you can do with the trophies
- [x] On the picture upload page, the user can select pictures for a boost
- [x] Used trophies give a boost for 24 hours
- [x] The used trophies are subtracted from the overall trophies
- [x] There is an icon that describes the benefits of trophies (an icon where you have to hover)

**Development Tasks FE**
- [x] sopra-fs22-group-20/client#125
- [x] sopra-fs22-group-20/client#127
- [x] sopra-fs22-group-20/client#128
- [x] sopra-fs22-group-20/client#129
- [x] sopra-fs22-group-20/client#132
- [x] sopra-fs22-group-20/client#133
- [x] sopra-fs22-group-20/client#134

**Development Tasks BE**
- [x] #230
- [x] #231

**Comment by kone54** [comment]
API GET call on every picture in order to get every picture’s current boost level and the missing trophies to get to the next boost level -> sent with the image from the get request to get the images?
